-- 审批流程配置表
CREATE TABLE `b_approve_process_config` (
  `id` varchar(50) NOT NULL COMMENT '主键ID',
  `process_name` varchar(100) NOT NULL COMMENT '流程名称',
  `process_type` varchar(50) NOT NULL COMMENT '流程类型（1：相似客户审批 2：客户信息变更审批 3：电话/微信跟进审批 4：电话/微信且满足三个一的跟进审批 5：上门拜访跟进审批 6：上门拜访且满足三个一的跟进审批 7：邀约到访跟进审批 8：邀约到访且满足三个一的跟进审批 9：自然来访跟进审批 10：自然来访且满足三个一的跟进审批 11：其他跟进审批 12：其他跟进且满足三个一的审批）',
  `level_type` varchar(20) NOT NULL COMMENT '级别类型（1：集团级 2：区域级 3：项目级）',
  `region_id` varchar(50) DEFAULT NULL COMMENT '区域ID（区域级时必填）',
  `project_id` varchar(50) DEFAULT NULL COMMENT '项目ID（项目级时必填）',
  `is_enabled` tinyint(1) DEFAULT 0 COMMENT '是否启用（0：禁用 1：启用）',
  `is_force` tinyint(1) DEFAULT 0 COMMENT '是否强制（0：否 1：是，集团级专用）',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(50) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_del` tinyint(1) DEFAULT 0 COMMENT '是否删除（0：否 1：是）',
  PRIMARY KEY (`id`),
  KEY `idx_process_type` (`process_type`),
  KEY `idx_level_type` (`level_type`),
  KEY `idx_region_id` (`region_id`),
  KEY `idx_project_id` (`project_id`),
  KEY `idx_is_enabled` (`is_enabled`),
  KEY `idx_is_del` (`is_del`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='审批流程配置表';

-- 审批流程节点表
CREATE TABLE `b_approve_process_node` (
  `id` varchar(50) NOT NULL COMMENT '主键ID',
  `process_config_id` varchar(50) NOT NULL COMMENT '流程配置ID',
  `node_name` varchar(100) NOT NULL COMMENT '节点名称',
  `node_type` varchar(20) NOT NULL COMMENT '节点类型（1：审批节点 2：抄送节点）',
  `node_order` int(11) NOT NULL COMMENT '节点顺序',
  `approval_jobs` text COMMENT '审批岗位（JSON格式，多个岗位用逗号分隔）',
  `cc_jobs` text COMMENT '抄送岗位（JSON格式，多个岗位用逗号分隔）',
  `timeout_days` int(11) DEFAULT 0 COMMENT '超时天数（0：不超时）',
  `is_required` tinyint(1) DEFAULT 1 COMMENT '是否必填（0：否 1：是）',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(50) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_del` tinyint(1) DEFAULT 0 COMMENT '是否删除（0：否 1：是）',
  PRIMARY KEY (`id`),
  KEY `idx_process_config_id` (`process_config_id`),
  KEY `idx_node_type` (`node_type`),
  KEY `idx_node_order` (`node_order`),
  KEY `idx_is_del` (`is_del`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='审批流程节点表';

-- 审批流程记录表
CREATE TABLE `b_approve_process_record` (
  `id` varchar(50) NOT NULL COMMENT '主键ID',
  `process_config_id` varchar(50) NOT NULL COMMENT '流程配置ID',
  `business_id` varchar(50) NOT NULL COMMENT '业务ID',
  `business_type` varchar(50) NOT NULL COMMENT '业务类型',
  `process_type` varchar(50) NOT NULL COMMENT '流程类型',
  `status` varchar(20) DEFAULT '1' COMMENT '状态（1：待审批 2：审批通过 3：驳回 4：超时驳回）',
  `apply_user_id` varchar(50) NOT NULL COMMENT '申请人ID',
  `apply_user_name` varchar(100) NOT NULL COMMENT '申请人姓名',
  `apply_user_job` varchar(50) DEFAULT NULL COMMENT '申请人岗位',
  `apply_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '申请时间',
  `approve_time` datetime DEFAULT NULL COMMENT '审批时间',
  `approve_user_id` varchar(50) DEFAULT NULL COMMENT '审批人ID',
  `approve_user_name` varchar(100) DEFAULT NULL COMMENT '审批人姓名',
  `approve_opinion` text COMMENT '审批意见',
  `timeout_time` datetime DEFAULT NULL COMMENT '超时时间',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(50) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_del` tinyint(1) DEFAULT 0 COMMENT '是否删除（0：否 1：是）',
  PRIMARY KEY (`id`),
  KEY `idx_process_config_id` (`process_config_id`),
  KEY `idx_business_id` (`business_id`),
  KEY `idx_business_type` (`business_type`),
  KEY `idx_process_type` (`process_type`),
  KEY `idx_status` (`status`),
  KEY `idx_apply_user_id` (`apply_user_id`),
  KEY `idx_is_del` (`is_del`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='审批流程记录表';

-- 审批流程节点记录表
CREATE TABLE `b_approve_process_node_record` (
  `id` varchar(50) NOT NULL COMMENT '主键ID',
  `process_record_id` varchar(50) NOT NULL COMMENT '流程记录ID',
  `node_id` varchar(50) NOT NULL COMMENT '节点ID',
  `node_name` varchar(100) NOT NULL COMMENT '节点名称',
  `node_type` varchar(20) NOT NULL COMMENT '节点类型（1：审批节点 2：抄送节点）',
  `node_order` int(11) NOT NULL COMMENT '节点顺序',
  `approval_user_id` varchar(50) DEFAULT NULL COMMENT '审批人ID',
  `approval_user_name` varchar(100) DEFAULT NULL COMMENT '审批人姓名',
  `approval_user_job` varchar(50) DEFAULT NULL COMMENT '审批人岗位',
  `status` varchar(20) DEFAULT '1' COMMENT '状态（1：待审批 2：审批通过 3：驳回 4：超时驳回）',
  `approval_time` datetime DEFAULT NULL COMMENT '审批时间',
  `approval_opinion` text COMMENT '审批意见',
  `timeout_time` datetime DEFAULT NULL COMMENT '超时时间',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(50) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_del` tinyint(1) DEFAULT 0 COMMENT '是否删除（0：否 1：是）',
  PRIMARY KEY (`id`),
  KEY `idx_process_record_id` (`process_record_id`),
  KEY `idx_node_id` (`node_id`),
  KEY `idx_node_type` (`node_type`),
  KEY `idx_status` (`status`),
  KEY `idx_approval_user_id` (`approval_user_id`),
  KEY `idx_is_del` (`is_del`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='审批流程节点记录表';
