server:
  # port: 8001
#  port: 8002
  #tomcat
  tomcat:
    uri-encoding: UTF-8
spring:
  profiles:
#    active: prod
#    active: pre
#    active: uat
#    active: dev
    active: sharding-simple  # 启用简化分库分表配置
  jackson:
    time-zone: GMT+8
  data:
    redis:
      repositories:
        enabled: false
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  #配置 Jpa
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
  activemq:
    broker-url:
  validationQuery: SELECT 1
  mvc:
    view:
      prefix: /WEB-INF/view/
# Mybatis配置
mybatis-plus:
  mapperLocations: classpath:mapper/mybaits/**.xml,classpath:mapper/mybaits/**/*.xml,classpath:mapper/publicpool/**.xml,classpath:mapper/customerlabel/**.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false


#七牛云
qiniu:
  # 文件大小 /M
  max-size: 15

#邮箱验证码有效时间/分钟
code:
  expiration: 5

#登录图形验证码有效时间/分钟
loginCode:
  expiration: 2
# 极光推送
jpush:
  masterSecret: e5a2c5787aedd7abec2ea063
  appkey: 972fa14adf6cf5d753d4df1c
  # true为生产环境，false为开发环境
  apnsProduction: true

param:
  interface:
    limit: 2000
    redisKey: wy:interface:limit
