server:
  port: 8001
  connection-timeout: 300000  # 毫秒，5分钟
  servlet:
    multipart:
      max-file-size: 100MB  # 单个文件大小
      max-request-size: 100MB  # 总请求大小

spring:
  # 启用ShardingSphere配置
  shardingsphere:
    # 数据源配置
    datasource:
      names: master,slave1,slave2
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.46.167:54319/wyzsb?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&useCursorFetch=true&defaultFetchSize=500&allowMultiQueries=true
        username: example_wyjt
        password: Example2025!@#
        # Druid连接池配置
        initial-size: 5
        min-idle: 5
        max-active: 200
        max-wait: 300000
        time-between-eviction-runs-millis: 90000
        min-evictable-idle-time-millis: 1800000
        test-while-idle: true
        test-on-borrow: true
        test-on-return: false
        validation-query: select 1
        filters: stat
      slave1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.46.168:54319/wyzsb?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&useCursorFetch=true&defaultFetchSize=500&allowMultiQueries=true
        username: example_wyjt
        password: Example2025!@#
        initial-size: 3
        min-idle: 3
        max-active: 100
        max-wait: 300000
        time-between-eviction-runs-millis: 90000
        min-evictable-idle-time-millis: 1800000
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        validation-query: select 1
        filters: stat
      slave2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.46.169:54319/wyzsb?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&useCursorFetch=true&defaultFetchSize=500&allowMultiQueries=true
        username: example_wyjt
        password: Example2025!@#
        initial-size: 3
        min-idle: 3
        max-active: 100
        max-wait: 300000
        time-between-eviction-runs-millis: 90000
        min-evictable-idle-time-millis: 1800000
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        validation-query: select 1
        filters: stat

    # 读写分离配置
    rules:
      readwrite-splitting:
        data-sources:
          readwrite_ds:
            type: STATIC
            props:
              write-data-source-name: master
              read-data-source-names: slave1,slave2
            load-balancer-name: round_robin
        load-balancers:
          round_robin:
            type: ROUND_ROBIN

      # 分表配置
      sharding:
        # 默认数据源
        default-data-source-name: readwrite_ds
        
        # 分表规则
        tables:
          b_project_clues:
            actual-data-nodes: readwrite_ds.b_project_clues_$->{202401..203012}
            table-strategy:
              standard:
                sharding-column: CreateTime
                sharding-algorithm-name: project_clues_monthly
            key-generate-strategy:
              column: ProjectClueId
              key-generator-name: snowflake

        # 分片算法配置
        sharding-algorithms:
          project_clues_monthly:
            type: CLASS_BASED
            props:
              strategy: STANDARD
              algorithmClassName: cn.visolink.config.ProjectCluesMonthlyShardingAlgorithm

        # 分布式主键生成器
        key-generators:
          snowflake:
            type: SNOWFLAKE
            props:
              worker-id: 1

    # 属性配置
    props:
      # 是否开启SQL日志
      sql-show: true
      # 是否开启简单SQL日志
      sql-simple: false
      # 执行器线程数
      executor-size: 16
      # 查询结果集是否缓存
      query-with-cipher-column: true

  # 关闭原有的数据源自动配置
  autoconfigure:
    exclude:
      - com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure

  # Druid监控配置
  datasource:
    druid:
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: Zsb_zs&7612~AUG
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 3000
          merge-sql: true
          slow-sql-log-period: 30000
        wall:
          enabled: false
          config:
            multi-statement-allow: true
            drop-table-allow: false
        slf4j:
          enabled: true
          statement-executable-sql-log-enable: true
          statement-parameter-set-log-enabled: true
          connection-log-enabled: false
          result-set-log-enabled: false

  #配置 Jpa
  jpa:
    hibernate:
      # 生产环境设置成 none，避免程序运行时自动更新数据库结构
      ddl-auto: none

  redis:
    host: 192.168.47.64
    port: 54318
    database: 2
    lettuce:
      pool:
        max-active: 500
        max-idle: 10
        max-wait: -1
        min-idle: 0
    timeout: 20000
    password: wyjt@2024

# MyBatis-Plus配置（保持原有配置）
mybatis-plus:
  mapperLocations: classpath:mapper/mybaits/**.xml,classpath:mapper/mybaits/**/*.xml,classpath:mapper/publicpool/**.xml,classpath:mapper/customerlabel/**.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false

# 日志配置
logging:
  level:
    cn.visolink: DEBUG
    org.apache.shardingsphere: DEBUG
    org.apache.shardingsphere.sharding: DEBUG
    org.apache.shardingsphere.readwritesplitting: DEBUG
    druid.sql: DEBUG

#jwt
jwt:
  header: Authorization
  secret: mySecret-webg
  refresh:
    secret: mySecret-refresh-web
    # token 1440 小时   一个月
    expiration: 31536000
  expiration: 31536000
  auth:
    # 授权路径
    path: /login
    # 获取用户信息
    account: /info
  backLogin:
    path: /backLogin

#是否开启 swagger-ui
swagger:
  enabled: false

# 日志配置  为空为项目跟目录下的logs  或者指定已经存在的目录
log:
  path: /vs/visoDemoProject/zhyx/app/tomcat-web-9002/logs/

sso:
  appUser: AUTH_SCRM
  privateKey: 6dh5w8ofvd5w8ycu
  url: https://sso.cifi.com.cn/siam/api/v2/token/tgt/auth
  tempTokenUrl: https://sso.cifi.com.cn/siam/oauth2.0/accessTokenByJson?client_id=AUTH_SCRM&client_secret=6dh5w8ofvd5w8ycu&response_type=code&redirect_uri=https%3A%2F%2Fscrm.cifi.com.cn%2F%23%2Fdashboard&code=
  accessUrl: https://sso.cifi.com.cn/siam/oauth2.0/profileByJson?access_token=

RedistributioinURL: https://scrm-api.cifi.com.cn/applet/service/updateMyOppZygw

MediaTypeURL: https://scrm-api.cifi.com.cn/applet/service/mediaTypeSyn

#文件路径
FTP_BASEPATH: /app/netdata/webFile
IMAGE_END_URL: https://scrm.cifi.com.cn/image/brokerWeb/
#图片上传路径
UPLOAD_URL: https://scrm-api-cifi.com.cn/applet/FileUpload/uploadFiles
#IMAGE_BASE_URL: https://scrm-api.cifi.com.cn/image/brokerWeb/
IMAGE_BASE_URL: /app/netdata/webFile
IMAGE_BASE_URL_W: /app/netdata/brokerWeb/
IMAGE_BASE_URL_QW: /app/netdata/qw/

#活动上传路径
IMAGE_ACTIVITY_URL: /app/netdata/activity/
IMAGE_ACTIVITY_URL_LOOK: https://scrm.cifi.com.cn/image/activity/

#新闻路径修改
IMAGE_TAG: https://scrm.cifi.com.cn/

appid: wxe4bf124e97c87ebd
appKey: 0b8b12722ab75a1d5ce899db9afa5d74

mapAppKey: 5PRBZ-VWJKD-NND4A-H2TMM-PJ7ZH-HNFFZ
mapUrl: https://apis.map.qq.com/ws/place/v1/search

#连接中台，获取全民经纪人运营分析
ZTJUrl: https://biboard-mgt.cifi.com.cn/datacollector/load/prcFactAgentProjXk
#连接中台，获取经纪人交易数据
ZTJJRURL: https://biboard-mgt.cifi.com.cn/datacollector/load/prcFactTradPfmcXk
#连接中台，获取活动交易数据
ZTACURL: https://biboard-mgt.cifi.com.cn/datacollector/load/prcFactActyTradXk
#连接中台，经纪人活动数据
ZTJJRHDURL: https://biboard-mgt.cifi.com.cn/datacollector/load/prcFactBrokerTradXk
#连接中台，大客户经理数据
ZTDKHURL: https://biboard-mgt.cifi.com.cn/datacollector/load/prcFactAcctTradXk

#更新redis数据
BROKERURL: https://sales.visolink.com/activity/RedisController/updateRedis
UPDATEREDISURL: https://sales.visolink.com/activity/RedisController/updateAwardInfo
#区分微信获取token 生产和测试
WeChatType: prod
WeChatTypeUrl: https://scrm-api.cifi.com.cn/man/system/weChatToken/getWeChatAccessToken

# 旺小宝接电说辞
WXBUrl: https://phone.cifi.com.cn/fileserver/file/playaudio/
#sqlserver 数据库配置
DBDurl: jdbc:sqlserver://10.30.2.90:1433;DatabaseName=dotnet_erp60
DBXurl: jdbc:sqlserver://10.30.2.90:1433;DatabaseName=dotnet_erp60
DBuser: myerp
DBpassword: Mysoft!@#123

XZSurl: jdbc:mysql://192.168.46.65:54319/erp_pro?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&useCursorFetch=true&defaultFetchSize=500&allowMultiQueries=true
XZSuser: putest
XZSpassword: '!WYjt@2025.0103XZSXT'

#定时任务数据源配置
druidDataSource:
  Url: jdbc:mysql://118.190.56.178:3306/{}?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&useCursorFetch=true&defaultFetchSize=500&allowMultiQueries=true
  Username: root
  Password: root
#销管系统数据源
xg:
  url: jdbc:mysql://10.129.16.218:3306/saleman
  username: xukeview
  password: XUKE#View_201015

PerformanceURL: https://scrm-api.cifi.com.cn/applet/service/performanceSyn

#公共对外接口路径
FOREIGNURL: https://scrm-api.cifi.com.cn/applet/service/
#同步置业顾问
ConsultantSyncURL: https://scrm-api.cifi.com.cn/applet/openTo/consultantSync

#获取公司数据库
CompanyDataUrl: https://sales.visolink.com/auth/customer/queryCompanyData
#获取聚客汇菜单
AppMenuUrl: https://sales.visolink.com/auth/customer/getAllAppMenus
#验证码请求接口
CODE_PATH: https://sales.visolink.com/auth/sms/sendQrSms

#企微token获取路径
WX_TOKEN_PATH: https://sales.visolink.com/auth/comwx/selectToken

#推送明源丢失客户
ISTOMYURL: https://gkt.zhongnangroup.cn/applet/service/addMyCst

#推送明源公共池更新
SENDMYPOOLURL: http://218.91.205.67:8082/apigate/CommonOpportunityPoolU

#短信模板
YJCODE: 000012
GBCODE: 000011

#审批回调：
SystemUrl: https://ydac.vanyang.com.cn/web/#/
#审批接口路径
StartProcess: http://esb.vanyang.com.cn/oa/sendOAWorkFlow

#移动案场推送OA消息接口
YDACSENDOAMESSAGEURL: http://esb.vanyang.com.cn/oa/sendOAMessage
YDACSENDOAMESSAGEAPPCODE: 3007
isSendOAMessage: 0
#移动案场跟进审批待办
YDACFOLLOWUPPENDINGURL: https://ydac.vanyang.com.cn/web/#/PendingfollowWhite
#移动案场转介审批待办
YDACREFERRALPENDINGURL: https://ydac.vanyang.com.cn/web/#/referralProcessedWhite
#移动案场公客池客户获取审批待办
YDACOBTAINCSTPENDINGURL: https://ydac.vanyang.com.cn/web/#/pendingReferralWhite

#Excel Url
ExcelUrl: /app/netdata/excel/
#Excel DownLoadUrl
DownLoadUrl: https://ydac.vanyang.com.cn/image/excel/

#外呼打通登录鉴权的密钥
outbound:
  secret: TkIEJwtmM8mhPcE8J3IofVfcMM72pOsU
  channelId: 545
  urlOp: http://192.168.47.61:9011/call/api/auth.Login/auth
  addUserOp: http://192.168.47.61:9011/call/api/seats.Seats/add
  updateUserOp: http://192.168.47.61:9011/call/api/seats.Seats/edit
  deleteUserOp: http://192.168.47.61:9011/call/api/seats.Seats/dele
  addOrgOp:  http://192.168.47.61:9011/call/api/seats.CrmStructure/add
  updateOrgOp:  http://192.168.47.61:9011/call/api/seats.CrmStructure/edi
  addRoleOp: http://192.168.47.61:9011/call/api/seats.CrmGroups/add
  updateRoleOp: http://192.168.47.61:9011/call/api/seats.CrmGroups/edit
  deleteHD: http://192.168.47.61:9011/call/api/crm.Leads/dele
  addRobot: http://192.168.47.61:9011/call/api/crm.Leads/addRobot
  addTheCall: http://192.168.47.61:9011/call/api/crm.Leads/addAll
  getTimeoutWarning: http://192.168.47.61:9011/admin/company.CompanyAccount/getOverCompanyStructureAccount
  uid: fdda5dae-bd5f-47e3-b440-fb5be49297bf
  did: a84fd6a0-3554-11e7-a3f8-5254007b6f02
  sid: '00000001'
  isCall: 1

# es服务器
elasticsearch:
  host: 192.168.46.66
  port: 9200

ed:
  # 公司名称
  commonFieldId: '43688bd0-c486-43b1-985f-6b0c465f5cf3'
  # 行业
  industryFieldId: '9c21b560-827f-4d8b-9245-72b70475756b'
  industryTwoFieldId: '8d6608a8-a8fd-465e-ad03-660b9475a18c'
  industryThreeFieldId: 'fd872e54-e344-418d-abe7-44924d8509d3'
  industryFourFieldId: 'd29784ba-282b-4716-8b3a-2d8937cf8141'
  # 地址
  provinceFieldId: 'b67557aa-7f1f-4f35-bfd8-5f1dfe2f9129'
  # 公司规模
  companyScaleFieldId: 'a551140e-5c0f-4ff5-988d-e782a188c165'
  # 成立日期
  establishYearsFieldId: '61feb2dc-75a2-46e4-b3bf-7808a31c48cf'
  # 营业状态
  registrationStatusFieldId: '09d70acb-72fa-4b00-9b52-ea8a7a6f195d'
  # 注册资本
  registeredCapitalFieldId: '0f76e534-ddfa-419c-8d71-c6d540f5add9'
  # 电话
  phoneFieldId: '10e8f620-9acc-498b-9756-2a356a4901e2'
  # 更多电话
  phoneFieldId2: 'e2601a0a-a284-429c-aa62-ff3f51d9cb13'
  # 法人
  legalPersonFieldId: 'a624d827-fad3-4487-92f3-ed2138afb8a6'
  # 企业类型
  companyTypeFieldId: '72858482-a461-477e-9a4a-4a2dbe3a4442'
  # 邮箱
  emailFieldId: '58efec6e-5d74-47be-87d1-59d2b8cdbf8f'
  # 邮编
  postCodeFieldId: '81632c61-6d3e-49d4-aba9-8d29aff848e2'
  # 网址
  webAddressFieldId: 'ac8e557c-6e49-422b-a779-717e5b764100'
  # 参保人数
  insuredPersonFieldId: '33d48b92-1a77-4103-8ded-f371aa70024e'
  # 年营业额
  annualRevenueFieldId: '9f8b0778-6664-491a-8c72-e06488c41566'
  # 人员规模
  staffSizeFieldId: 'dcbbf859-cf3e-4910-8a6f-518de63e8a86'

# 定时任务开关
scheduler:
  enabled: true
# 权限拦截器配置
permission:
  interceptor:
    enabled: false
  check:
    enabled: true
    cache-enabled: true
    cache-expire: 300

# 数据加密配置
encrypt:
  enabled: true
  algorithm: aes
  aes:
    key: visolink2024key!
    use-custom-key: false
  # 加密排除配置
  exclude:
    paths:
      - /login
      - /logout
      - /error
      - /swagger-ui/**
      - /static/**
    # 白名单类和方法配置
    whitelist:
      classes:
      methods:
        - "cn.visolink.system.channel.controller.ProjectCluesController#getGlAllocationPropertyConsultantZygwCall"
        - "cn.visolink.system.channel.controller.ProjectCluesController#isRobotPermissions"
        - "cn.visolink.system.channel.controller.ProjectCluesController#getCallProjectRule"
        - "cn.visolink.system.channel.controller.ProjectCluesController#callTurnTheClue"
        - "cn.visolink.common.security.rest.AuthenticationController#authentication"

generator:
  enabled: false

pagehelper:
  helperDialect: mysql
